<?php $_helper = Mage::helper('sidecat'); ?>
<?php $showtype = $_helper->getShowType();?>
<?php 
	$show_font = $_helper->getShowFont();
	$getCategoryColor = $_helper->getCategoryColor();
	$getCategoryBg = $_helper->getCategoryBg();
	$getCategoryLabel = $_helper->getCategoryLabel();
	$getCategoryTextColor = $_helper->getCategoryTextColor();	
 ?>
<?php echo "<style>
	#sidenav li a {
		text-transform:  ".$show_font." !important;
		color: ".$getCategoryColor." !important;
	}
	.sideNavBg{
		background: ".$getCategoryBg." !important;
	}
	.catLabel{
		color: ".$getCategoryTextColor." !important;
	}
</style>"; ?>
<?php $_menu = $this->renderCategoriesMenuHtml(0,'level-top') ?>
<?php if($_helper->isEnabled()): ?>
	<?php if($showtype == 'static'):?>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/matrix/sidecat/static.css');?>" media="all" />
		<?php if($_menu): ?>
		<div class="block block-category-nav">
			<div class="block-title sideNavBg">
				<strong><span class="catLabel"><?php echo $getCategoryLabel; ?></span></strong>
			</div>
			<div class="block-content">
				<ul id="sidenav">
					<?php echo $_menu ?>
				</ul>
			</div>	
		</div>
		<?php endif ?>
	<?php elseif ($showtype == 'click-2-click'):?>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/matrix/sidecat/click.css');?>" media="all" />
		<script src="http://jqueryjs.googlecode.com/files/jquery-1.3.2.min.js" type="text/javascript"></script>
		<script type="text/javascript">
			var $j = jQuery.noConflict(); 
			$j(document).ready(function () {
			  $j('#sidenav > li > a.show-cat').click(function(){
				$j('#sidenav li ul').slideUp();
				if (!$j(this).hasClass('active')){				  
				  $j(this).next().slideToggle();
				  $j('#sidenav li a.show-cat').removeClass('active');
				  $j(this).addClass('active');
				}
				else if ($j(this).hasClass('active')) {
					$j(this).removeClass('active');
				}
			  });
			  $j('#sidenav > li > ul > li > a.show-cat').click(function(){
				$j('#sidenav li ul li ul').slideUp();
				if (!$j(this).hasClass('active')){
				  $j(this).next().slideToggle();
				  $j('#sidenav li ul li a.show-cat').removeClass('active');
				  $j(this).addClass('active');
				}
				else if ($j(this).hasClass('active')) {
					$j(this).removeClass('active');
				}
			  });
			});
		</script>
		<?php if($_menu): ?>
		<div class="block block-category-nav">
			<div class="block-title sideNavBg">
				<strong><span class="catLabel"><?php echo $getCategoryLabel; ?></span></strong>
			</div>
			<div class="block-content">
				<ul id="sidenav">
					<?php echo $_menu ?>
				</ul>
			</div>	
		</div>
		<?php endif ?>
	<?php elseif ($showtype == 'fly-out'):?>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/matrix/sidecat/fly-out.css')?>" media="screen">
		<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/matrix/sidecat/jquery-1.2.6.min.js')?>"></script>
		<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/matrix/sidecat/hoverIntent.js')?>"></script>
		<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/matrix/sidecat/superfish.js')?>"></script>
		<script type="text/javascript">
			jQuery.noConflict();
			jQuery(function(){
						jQuery('ul.sf-menu').superfish();
					});
		</script>
		<?php if($_menu): ?>
		<div class="block block-category-nav">
			<div class="block-title sideNavBg">
				<strong><span class="catLabel"><?php echo $getCategoryLabel; ?></span></strong>
			</div>
			<div class="block-content">
				<ul class="sf-menu" id="left-nav">					
					<?php echo $_menu ?>
				</ul>
			</div>	
		</div>
		<?php endif ?>
	<?php endif ?>	
<?php endif ?>	
